name: odoo_call_test
dependencies:
  http: any
  intl: ^0.19.0
  equatable: any
  odoo_repository: ^0.5.8
  odoo_rpc: ^0.5.2
  connectivity: ^3.0.6
  hive: ^2.2.3
  crypto: ^3.0.3
environment:
  sdk: '^3.2.0'